document.addEventListener('DOMContentLoaded',function(){
var hamburger=document.querySelector('.hamburger'),navLinks=document.querySelector('.nav-links'),navOverlay=document.querySelector('.nav-overlay');
if(hamburger){hamburger.addEventListener('click',function(){navLinks.classList.toggle('active');if(navOverlay)navOverlay.classList.toggle('active');var s=hamburger.querySelectorAll('span');hamburger.classList.toggle('open');if(hamburger.classList.contains('open')){s[0].style.transform='rotate(45deg) translate(5px,6px)';s[1].style.opacity='0';s[2].style.transform='rotate(-45deg) translate(5px,-6px)'}else{s[0].style.transform='none';s[1].style.opacity='1';s[2].style.transform='none'}})}
if(navOverlay){navOverlay.addEventListener('click',function(){navLinks.classList.remove('active');navOverlay.classList.remove('active');if(hamburger){hamburger.classList.remove('open');var s=hamburger.querySelectorAll('span');s[0].style.transform='none';s[1].style.opacity='1';s[2].style.transform='none'}})}
document.querySelectorAll('.nav-links a').forEach(function(l){l.addEventListener('click',function(){if(window.innerWidth<=768){navLinks.classList.remove('active');if(navOverlay)navOverlay.classList.remove('active')}})});
document.querySelectorAll('.lang-switcher a').forEach(function(b){b.addEventListener('click',function(e){e.preventDefault();document.querySelectorAll('.lang-switcher a').forEach(function(x){x.classList.remove('active')});this.classList.add('active');alert('Language: '+this.textContent.trim()+'\n\n(Multilingual via WPML/Polylang in production)')})});
var btt=document.querySelector('.back-to-top');if(btt){window.addEventListener('scroll',function(){btt.classList.toggle('show',window.scrollY>300)});btt.addEventListener('click',function(){window.scrollTo({top:0,behavior:'smooth'})})}
var cb=document.querySelector('.cookie-banner'),ca=document.getElementById('cookie-accept'),cd=document.getElementById('cookie-decline');
if(cb&&!localStorage.getItem('dc_cookie_consent'))setTimeout(function(){cb.classList.add('show')},1500);
if(ca)ca.addEventListener('click',function(){localStorage.setItem('dc_cookie_consent','accepted');cb.classList.remove('show')});
if(cd)cd.addEventListener('click',function(){localStorage.setItem('dc_cookie_consent','declined');cb.classList.remove('show')});
var nf=document.getElementById('newsletter-form');
if(nf)nf.addEventListener('submit',function(e){e.preventDefault();var ei=this.querySelector('input[type="email"]'),cc=document.getElementById('newsletter-consent'),em=ei?ei.value.trim():'';if(!em||!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(em)){alert('Please enter a valid email.');return}if(cc&&!cc.checked){alert('DPDP Act 2023: Please provide explicit consent.');return}alert('Thank you for subscribing! \uD83D\uDE4F');ei.value='';if(cc)cc.checked=false});
document.querySelectorAll('.category-filters button').forEach(function(b){b.addEventListener('click',function(){document.querySelectorAll('.category-filters button').forEach(function(x){x.classList.remove('active')});this.classList.add('active');var cat=this.getAttribute('data-filter');document.querySelectorAll('.product-card[data-category]').forEach(function(c){c.style.display=(cat==='all'||c.getAttribute('data-category')===cat)?'':'none'})})});
var cartCount=0,cartEl=document.querySelector('.cart-count');
document.querySelectorAll('.add-to-cart-btn').forEach(function(b){b.addEventListener('click',function(e){e.preventDefault();cartCount++;if(cartEl){cartEl.textContent=cartCount;cartEl.style.transform='scale(1.4)';setTimeout(function(){cartEl.style.transform='scale(1)'},200)}var t=this.textContent,s=this;this.textContent='\u2713 Added!';this.style.background='#27AE60';setTimeout(function(){s.textContent=t;s.style.background=''},1200)})});
document.querySelectorAll('.buy-now-btn').forEach(function(b){b.addEventListener('click',function(e){e.preventDefault();alert('Redirecting to checkout...\n\n(WooCommerce + Razorpay in production)')})});
document.querySelectorAll('.inquiry-form').forEach(function(f){f.addEventListener('submit',function(e){e.preventDefault();alert('Thank you! \uD83D\uDE4F Our team will respond within 24 hours.');f.reset()})});
document.querySelectorAll('a[href^="#"]').forEach(function(a){a.addEventListener('click',function(e){var t=this.getAttribute('href');if(t&&t!=='#'){e.preventDefault();var el=document.querySelector(t);if(el)el.scrollIntoView({behavior:'smooth',block:'start'})}})});
var fs=document.createElement('style');fs.textContent='@keyframes fadeIn{from{opacity:0;transform:translateY(20px)}to{opacity:1;transform:translateY(0)}}.fade-in{opacity:0;transform:translateY(20px);transition:all .6s ease}.fade-in.visible{opacity:1;transform:translateY(0)}';document.head.appendChild(fs);
var obs=new IntersectionObserver(function(en){en.forEach(function(e){if(e.isIntersecting)e.target.classList.add('visible')})},{threshold:.1,rootMargin:'0px 0px -50px 0px'});
document.querySelectorAll('.vertical-card,.product-card,.service-card,.event-card,.testimonial-card,.blog-card,.team-card,.contact-info-item').forEach(function(el){el.classList.add('fade-in');obs.observe(el)});
});